In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('classic')

In [2]:
df_train = pd.read_csv('Train.csv')
df_test = pd.read_csv('Test.csv')

In [3]:
df_train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

# Build a solution that should able to predict the sales of the different stores of Big Mart

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [5]:
df_train.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [6]:
 df_test.isnull().sum()

Item_Identifier                 0
Item_Weight                   976
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1606
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [7]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [8]:
df_train.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Item_Weight,7060.0,12.857645,4.643456,4.555,8.773750,12.600000,16.850000,21.350000
Item_Visibility,8523.0,0.066132,0.051598,0.000,0.026989,0.053931,0.094585,0.328391
Item_MRP,8523.0,140.992782,62.275067,31.290,93.826500,143.012800,185.643700,266.888400
Outlet_Establishment_Year,8523.0,1997.831867,8.371760,1985.000,1987.000000,1999.000000,2004.000000,2009.000000
Item_Outlet_Sales,8523.0,2181.288914,1706.499616,33.290,834.247400,1794.331000,3101.296400,13086.964800

In [9]:
df_train['Item_Weight'].describe()

count    7060.000000
mean       12.857645
std         4.643456
min         4.555000
25%         8.773750
50%        12.600000
75%        16.850000
max        21.350000
Name: Item_Weight, dtype: float64

# Filling Missing Values

### Item Weight is numeric value so we fill it with Mean value

In [10]:
item_wt_mean = df_train['Item_Weight'].mean()
df_train['Item_Weight'].fillna(item_wt_mean, inplace=True)
df_test['Item_Weight'].fillna(item_wt_mean, inplace=True)

In [16]:
df_train.isnull().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

### Outlet Size is categorical value so we fill it with Mode value

In [22]:
outlet_size_mode = df_train['Outlet_Size'].mode()[0]
df_train['Outlet_Size'].fillna(outlet_size_mode, inplace=True)
df_test['Outlet_Size'].fillna(outlet_size_mode, inplace=True)

In [23]:
df_train.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [24]:
df_test.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
dtype: int64

In [25]:
df_train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

# Selecting features based on general requirements

In [26]:
df_train.drop(['Item_Identifier', 'Outlet_Identifier', 'Outlet_Establishment_Year'], axis=1, inplace=True)

In [29]:
df_train.head()

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,9.30,Low Fat,0.016047,Dairy,249.8092,Medium,Tier 1,Supermarket Type1,3735.1380
1,5.92,Regular,0.019278,Soft Drinks,48.2692,Medium,Tier 3,Supermarket Type2,443.4228
2,17.50,Low Fat,0.016760,Meat,141.6180,Medium,Tier 1,Supermarket Type1,2097.2700
3,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,Medium,Tier 3,Grocery Store,732.3800
4,8.93,Low Fat,0.000000,Household,53.8614,High,Tier 3,Supermarket Type1,994.7052

# Exploratory data analysis using Dtale library

In [65]:
import dtale as dt

ImportError: cannot import name 'escape' from 'jinja2' (C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\jinja2\__init__.py)

In [63]:
conda install dtale -c conda-forge

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Admin\anaconda3

  added / updated specs:
    - dtale


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    brotli-python-1.0.9        |   py39h415ef7b_7         334 KB  conda-forge
    conda-4.14.0               |   py39hcbf5309_0         1.0 MB  conda-forge
    dash-2.6.1                 |     pyhd8ed1ab_0         7.7 MB  conda-forge
    dash-bootstrap-components-1.2.1|     pyhd8ed1ab_0         111 KB  conda-forge
    dash-core-components-2.0.0 |     pyhd8ed1ab_1           7 KB  conda-forge
    dash-daq-0.5.0             |     pyh9f0ad1d_1         545 KB  conda-forge
    dash-html-components-2.0.0 |     pyhd8ed1ab_1           8 KB  conda-forge
    dash_colorscales-0.0.4     |     pyh9f0ad1d_0          59 KB  conda-forge
    dtale-2.8.1                |     pyhd8ed1ab_0        10.4 MB  conda-forge
    flask-compress-1.12        |     pyhd8ed1ab_1          15 KB  conda-forge
    lz4-4.0.0                  |   py39h0878066_2          80 KB  conda-forge
    missingno-0.4.2            |             py_1          12 KB  conda-forge
    python_abi-3.9             |           2_cp39           4 KB  conda-forge
    squarify-0.4.3             |             py_0           7 KB  conda-forge
    strsimpy-0.1.9             |     pyh9f0ad1d_0          22 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        20.3 MB

The following NEW packages will be INSTALLED:

  brotli-python      conda-forge/win-64::brotli-python-1.0.9-py39h415ef7b_7
  dash               conda-forge/noarch::dash-2.6.1-pyhd8ed1ab_0
  dash-bootstrap-co~ conda-forge/noarch::dash-bootstrap-components-1.2.1-pyhd8ed1ab_0
  dash-core-compone~ conda-forge/noarch::dash-core-components-2.0.0-pyhd8ed1ab_1
  dash-daq           conda-forge/noarch::dash-daq-0.5.0-pyh9f0ad1d_1
  dash-html-compone~ conda-forge/noarch::dash-html-components-2.0.0-pyhd8ed1ab_1
  dash_colorscales   conda-forge/noarch::dash_colorscales-0.0.4-pyh9f0ad1d_0
  dtale              conda-forge/noarch::dtale-2.8.1-pyhd8ed1ab_0
  flask-compress     conda-forge/noarch::flask-compress-1.12-pyhd8ed1ab_1
  lz4                conda-forge/win-64::lz4-4.0.0-py39h0878066_2
  missingno          conda-forge/noarch::missingno-0.4.2-py_1
  python_abi         conda-forge/win-64::python_abi-3.9-2_cp39
  squarify           conda-forge/noarch::squarify-0.4.3-py_0
  strsimpy           conda-forge/noarch::strsimpy-0.1.9-pyh9f0ad1d_0

The following packages will be SUPERSEDED by a higher-priority channel:

  conda              pkgs/main::conda-4.14.0-py39haa95532_0 --> conda-forge::conda-4.14.0-py39hcbf5309_0



Downloading and Extracting Packages

flask-compress-1.12  | 15 KB     |            |   0%
flask-compress-1.12  | 15 KB     | ########## | 100%
flask-compress-1.12  | 15 KB     | ########## | 100%

dash-html-components | 8 KB      |            |   0%
dash-html-components | 8 KB      | ########## | 100%
dash-html-components | 8 KB      | ########## | 100%

dash-daq-0.5.0       | 545 KB    |            |   0%
dash-daq-0.5.0       | 545 KB    | 2          |   3%
dash-daq-0.5.0       | 545 KB    | #7         |  18%
dash-daq-0.5.0       | 545 KB    | ####1      |  41%
dash-daq-0.5.0       | 545 KB    | #####5     |  56%
dash-daq-0.5.0       | 545 KB    | #######9   |  79%
dash-daq-0.5.0       | 545 KB    | #########  |  91%
dash-daq-0.5.0       | 545 KB    | ########## | 100%
dash-daq-0.5.0       | 545 KB    | ########## | 100%

dash-2.6.1           | 7.7 MB    |            |   0%
dash-2.6.1           | 7.7 MB    |            |   0%

Note: you may need to restart the kernel to use updated packages.dash-2.6.1           | 7.7 MB    |            |   1%
dash-2.6.1           | 7.7 MB    | 1          |   2%
dash-2.6.1           | 7.7 MB    | 3          |   3%
dash-2.6.1           | 7.7 MB    | 4          |   4%
dash-2.6.1           | 7.7 MB    | 5          |   5%
dash-2.6.1           | 7.7 MB    | 6          |   7%
dash-2.6.1           | 7.7 MB    | 9          |   9%
dash-2.6.1           | 7.7 MB    | #          |  11%
dash-2.6.1           | 7.7 MB    | #3         |  13%
dash-2.6.1           | 7.7 MB    | #5         |  15%
dash-2.6.1           | 7.7 MB    | #7         |  17%
dash-2.6.1           | 7.7 MB    | #9         |  20%

dash-2.6.1           | 7.7 MB    | ##2        |  23%
dash-2.6.1           | 7.7 MB    | ##5        |  26%
dash-2.6.1           | 7.7 MB    | ##8        |  29%
dash-2.6.1           | 7.7 MB    | ###1       |  31%
dash-2.6.1           | 7.7 MB    | ###3       |  34%
dash-2.6.1           | 7.7 MB    | ###8       |  38%
dash-2.6.1           | 7.7 MB    | ####2      |  42%
dash-2.6.1           | 7.7 MB    | ####6      |  47%
dash-2.6.1           | 7.7 MB    | #####      |  51%
dash-2.6.1           | 7.7 MB    | #####5     |  56%
dash-2.6.1           | 7.7 MB    | ######     |  61%
dash-2.6.1           | 7.7 MB    | ######5    |  66%
dash-2.6.1           | 7.7 MB    | #######    |  71%
dash-2.6.1           | 7.7 MB    | ########2  |  82%
dash-2.6.1           | 7.7 MB    | ########9  |  89%
dash-2.6.1           | 7.7 MB    | #########6 |  97%
dash-2.6.1           | 7.7 MB    | ########## | 100%

dash_colorscales-0.0 | 59 KB     |            |   0%
dash_colorscales-0.0 | 59 KB     | ##7        |  27%
dash_colorscales-0.0 | 59 KB     | ########## | 100%

dtale-2.8.1          | 10.4 MB   |            |   0%
dtale-2.8.1          | 10.4 MB   |            |   0%
dtale-2.8.1          | 10.4 MB   |            |   1%
dtale-2.8.1          | 10.4 MB   | 1          |   1%
dtale-2.8.1          | 10.4 MB   | 1          |   2%
dtale-2.8.1          | 10.4 MB   | 2          |   3%
dtale-2.8.1          | 10.4 MB   | 3          |   3%
dtale-2.8.1          | 10.4 MB   | 3          |   4%
dtale-2.8.1          | 10.4 MB   | 5          |   6%
dtale-2.8.1          | 10.4 MB   | 7          |   7%
dtale-2.8.1          | 10.4 MB   | 7          |   8%
dtale-2.8.1          | 10.4 MB   | 8          |   9%
dtale-2.8.1          | 10.4 MB   | 9          |   9%
dtale-2.8.1          | 10.4 MB   | 9          |  10%
dtale-2.8.1          | 10.4 MB   | #          |  10%
dtale-2.8.1          | 10.4 MB   | #          |  11%
dtale-2.8.1          | 10.4 MB   | #2         |  12%
dtale-2.8.1          | 10.4 MB   | #3         |  13%
dtale-2.8.1          | 10.4 MB   | #3         |  14%
dtale-2.8.1          | 10.4 MB   | #4         |  15%
dtale-2.8.1          | 10.4 MB   | #5         |  15%
dtale-2.8.1          | 10.4 MB   | #6         |  16%
dtale-2.8.1          | 10.4 MB   | #6         |  17%
dtale-2.8.1          | 10.4 MB   | #7         |  18%
dtale-2.8.1          | 10.4 MB   | #8         |  18%
dtale-2.8.1          | 10.4 MB   | #9         |  19%
dtale-2.8.1          | 10.4 MB   | ##         |  21%
dtale-2.8.1          | 10.4 MB   | ##1        |  22%
dtale-2.8.1          | 10.4 MB   | ##3        |  23%
dtale-2.8.1          | 10.4 MB   | ##4        |  25%
dtale-2.8.1          | 10.4 MB   | ##5        |  26%
dtale-2.8.1          | 10.4 MB   | ##7        |  27%
dtale-2.8.1          | 10.4 MB   | ##8        |  29%
dtale-2.8.1          | 10.4 MB   | ###        |  31%
dtale-2.8.1          | 10.4 MB   | ###2       |  32%
dtale-2.8.1          | 10.4 MB   | ###4       |  34%
dtale-2.8.1          | 10.4 MB   | ###6       |  36%
dtale-2.8.1          | 10.4 MB   | ###8       |  38%
dtale-2.8.1          | 10.4 MB   | ####       |  40%
dtale-2.8.1          | 10.4 MB   | ####2      |  43%
dtale-2.8.1          | 10.4 MB   | ####5      |  45%
dtale-2.8.1          | 10.4 MB   | ####7      |  48%
dtale-2.8.1          | 10.4 MB   | #####      |  50%
dtale-2.8.1          | 10.4 MB   | #####3     |  53%
dtale-2.8.1          | 10.4 MB   | #####5     |  56%
dtale-2.8.1          | 10.4 MB   | #####8     |  58%
dtale-2.8.1          | 10.4 MB   | ######3    |  64%
dtale-2.8.1          | 10.4 MB   | ######7    |  67%
dtale-2.8.1          | 10.4 MB   | #######1   |  71%
dtale-2.8.1          | 10.4 MB   | #######5   |  75%
dtale-2.8.1          | 10.4 MB   | #######9   |  79%
dtale-2.8.1          | 10.4 MB   | ########3  |  83%
dtale-2.8.1          | 10.4 MB   | ########8  |  88%
dtale-2.8.1          | 10.4 MB   | #########2 |  92%
dtale-2.8.1          | 10.4 MB   | #########6 |  96%
dtale-2.8.1          | 10.4 MB   | ########## | 100%

lz4-4.0.0            | 80 KB     |            |   0%
lz4-4.0.0            | 80 KB     | ##         |  20%
lz4-4.0.0            | 80 KB     | ########## | 100%
lz4-4.0.0            | 80 KB     | ########## | 100%

missingno-0.4.2      | 12 KB     |            |   0%
missingno-0.4.2      | 12 KB     | ########## | 100%
missingno-0.4.2      | 12 KB     | ########## | 100%

squarify-0.4.3       | 7 KB      |            |   0%
squarify-0.4.3       | 7 KB      | ########## | 100%
squarify-0.4.3       | 7 KB      | ########## | 100%

dash-bootstrap-compo | 111 KB    |            |   0%
dash-bootstrap-compo | 111 KB    | #4         |  14%
dash-bootstrap-compo | 111 KB    | ########6  |  86%
dash-bootstrap-compo | 111 KB    | ########## | 100%
dash-bootstrap-compo | 111 KB    | ########## | 100%

dash-core-components | 7 KB      |            |   0%
dash-core-components | 7 KB      | ########## | 100%
dash-core-components | 7 KB      | ########## | 100%

brotli-python-1.0.9  | 334 KB    |            |   0%
brotli-python-1.0.9  | 334 KB    | 4          |   5%
brotli-python-1.0.9  | 334 KB    | 9          |  10%
brotli-python-1.0.9  | 334 KB    | #4         |  14%
brotli-python-1.0.9  | 334 KB    | #9         |  19%
brotli-python-1.0.9  | 334 KB    | ##3        |  24%
brotli-python-1.0.9  | 334 KB    | ###3       |  33%
brotli-python-1.0.9  | 334 KB    | ###8       |  38%
brotli-python-1.0.9  | 334 KB    | ####3      |  43%
brotli-python-1.0.9  | 334 KB    | #####2     |  53%
brotli-python-1.0.9  | 334 KB    | ######2    |  62%
brotli-python-1.0.9  | 334 KB    | ######6    |  67%
brotli-python-1.0.9  | 334 KB    | #######1   |  72%
brotli-python-1.0.9  | 334 KB    | #######6   |  77%
brotli-python-1.0.9  | 334 KB    | ########1  |  81%
brotli-python-1.0.9  | 334 KB    | ########6  |  86%
brotli-python-1.0.9  | 334 KB    | #########5 |  96%
brotli-python-1.0.9  | 334 KB    | ########## | 100%
brotli-python-1.0.9  | 334 KB    | ########## | 100%

strsimpy-0.1.9       | 22 KB     |            |   0%
strsimpy-0.1.9       | 22 KB     | #######3   |  73%
strsimpy-0.1.9       | 22 KB     | ########## | 100%
strsimpy-0.1.9       | 22 KB     | ########## | 100%

python_abi-3.9       | 4 KB      |            |   0%
python_abi-3.9       | 4 KB      | ########## | 100%
python_abi-3.9       | 4 KB      | ########## | 100%

conda-4.14.0         | 1.0 MB    |            |   0%
conda-4.14.0         | 1.0 MB    | 1          |   2%
conda-4.14.0         | 1.0 MB    | 3          |   3%
conda-4.14.0         | 1.0 MB    | 4          |   5%
conda-4.14.0         | 1.0 MB    | 6          |   6%
conda-4.14.0         | 1.0 MB    | 7          |   8%
conda-4.14.0         | 1.0 MB    | 9          |   9%
conda-4.14.0         | 1.0 MB    | #          |  11%
conda-4.14.0         | 1.0 MB    | #2         |  12%
conda-4.14.0         | 1.0 MB    | #3         |  14%
conda-4.14.0         | 1.0 MB    | #5         |  15%
conda-4.14.0         | 1.0 MB    | #6         |  17%
conda-4.14.0         | 1.0 MB    | #8         |  18%
conda-4.14.0         | 1.0 MB    | #9         |  20%
conda-4.14.0         | 1.0 MB    | ##1        |  21%
conda-4.14.0         | 1.0 MB    | ##2        |  23%
conda-4.14.0         | 1.0 MB    | ##4        |  25%
conda-4.14.0         | 1.0 MB    | ##6        |  26%
conda-4.14.0         | 1.0 MB    | ##7        |  28%
conda-4.14.0         | 1.0 MB    | ##9        |  29%
conda-4.14.0         | 1.0 MB    | ###        |  31%
conda-4.14.0         | 1.0 MB    | ###3       |  34%
conda-4.14.0         | 1.0 MB    | ###5       |  35%
conda-4.14.0         | 1.0 MB    | ###6       |  37%
conda-4.14.0         | 1.0 MB    | ###8       |  38%
conda-4.14.0         | 1.0 MB    | ###9       |  40%
conda-4.14.0         | 1.0 MB    | ####1      |  41%
conda-4.14.0         | 1.0 MB    | ####2      |  43%
conda-4.14.0         | 1.0 MB    | ####4      |  44%
conda-4.14.0         | 1.0 MB    | ####5      |  46%
conda-4.14.0         | 1.0 MB    | ####7      |  47%
conda-4.14.0         | 1.0 MB    | ####9      |  49%
conda-4.14.0         | 1.0 MB    | #####      |  51%
conda-4.14.0         | 1.0 MB    | #####2     |  52%
conda-4.14.0         | 1.0 MB    | #####3     |  54%
conda-4.14.0         | 1.0 MB    | #####5     |  55%
conda-4.14.0         | 1.0 MB    | #####8     |  58%
conda-4.14.0         | 1.0 MB    | #####9     |  60%
conda-4.14.0         | 1.0 MB    | ######2    |  63%
conda-4.14.0         | 1.0 MB    | ######4    |  64%
conda-4.14.0         | 1.0 MB    | ######5    |  66%
conda-4.14.0         | 1.0 MB    | ######7    |  67%
conda-4.14.0         | 1.0 MB    | ######8    |  69%
conda-4.14.0         | 1.0 MB    | #######    |  70%
conda-4.14.0         | 1.0 MB    | #######2   |  72%
conda-4.14.0         | 1.0 MB    | #######3   |  74%
conda-4.14.0         | 1.0 MB    | #######5   |  75%
conda-4.14.0         | 1.0 MB    | #######6   |  77%
conda-4.14.0         | 1.0 MB    | #######8   |  78%
conda-4.14.0         | 1.0 MB    | #######9   |  80%
conda-4.14.0         | 1.0 MB    | ########1  |  81%
conda-4.14.0         | 1.0 MB    | ########4  |  84%
conda-4.14.0         | 1.0 MB    | ########7  |  87%
conda-4.14.0         | 1.0 MB    | ########8  |  89%
conda-4.14.0         | 1.0 MB    | #########  |  90%
conda-4.14.0         | 1.0 MB    | #########3 |  93%
conda-4.14.0         | 1.0 MB    | #########4 |  95%
conda-4.14.0         | 1.0 MB    | #########6 |  97%
conda-4.14.0         | 1.0 MB    | #########8 |  98%
conda-4.14.0         | 1.0 MB    | #########9 | 100%
conda-4.14.0         | 1.0 MB    | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Retrieving notices: ...working... done